### PR TITLE
DOP-2778: Fix side nav items with children so they collapse on click

### PR DESCRIPTION
**Pull request by gjchong25**
### Stories/Links:

[DOP-2778](https://jira.mongodb.org/browse/DOP-2778)

### Staging Links:

[Realm Staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/realm/grace.chong/DOP-2778/index.html)

### CODE REVIEW

**Review by allisonmui9 — APPROVED** [review]
so speedy. very nice lgtm thank you!

**Review by rayangler — COMMENTED** [review]
Changes LGTM, but I wanted to bring up that if you scroll down a page that has nested pages (example: [Tutorial](https://docs-mongodbcom-integration.corp.mongodb.com/master/realm/grace.chong/DOP-2778/tutorial/)), and then click on the side nav item that corresponds to that same page to close the nested items, you end up back at the top of the page (but the side nav item closes successfully!).

Is this interaction okay?

**Comment by allisonmui9** [comment]
> Tutorial

Oooooo .... Raymund good catch. Honestly, I'm not sure how we should address it. It's in production now, but I haven't heard any feedback regarding the behavior. I'm okay with leaving it as is and monitoring for any feedback in the future! 

Thanks :)

**Review by rayangler — APPROVED** [review]
Sure, that sounds good to me. Thanks @allisonmui9 and @gjchong25 !

LGTM!

**Pull request merged**
