### PR TITLE
DOP-2575: palette update

### PR DESCRIPTION
**Pull request by crisatmongo**
[DOP-2575](https://jira.mongodb.org/browse/DOP-2575) (Palette update)
https://jira.mongodb.org/browse/DOP-2575

Updated all instances of uiColors to palette in src per leafygreen updates. Spot-checked below pages to ensure no visual discrepancies after update.

Staging Links:
Server docs: https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/cris.newsome/DOP-2575-palette-update/
Cloud docs: https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/cris.newsome/DOP-2575-palette-update/
Guides: https://docs-mongodbcom-integration.corp.mongodb.com/master/guides/cris.newsome/DOP-2575-palette-update/
Realm: https://docs-mongodbcom-integration.corp.mongodb.com/master/realm/cris.newsome/DOP-2575-palette-update/

### CODE REVIEW

**Comment by schmalliso** [comment]
The chapter badges/pills/whatever (not sure what they're actually called) in Guides are using the wrong color for the words and it looks a little crazy - I suspect we need to set those pills to a different color rather than the really bright green.

Screen Shot 2022-09-20 at 10 28 47 AM

**Review by allisonmui9 — CHANGES_REQUESTED** [review]
Server
- It's looking like the top margin before the 'What is MongoDB' header has become quite squished. Does that have something to do with this change or something else? 

Guides
- Yes, I agree with Allison on the colors of the chapter tags. 
- Let's change the colors to: background green light 3 and text MDB black. 
- The same applies to this screenshot! Let's change the chapter tag color to background green light 3 and text MDB black. Let's change the check, line, and lightning bolt to green dark 1.  
Screen Shot 2022-09-20 at 10 59 58 AM
- I wasn't able to find a quiz example. Could you share what that looks like with the new palette?

**Comment by rayangler** [comment]
Just wondering: should the base branch for this PR be `branding-master`?

**Comment by seungpark** [comment]
> 

yes destination should be branding-master. we should generally branch off branding-master, but seeing we have an non-brand upcoming release, merging to branding-master should be good

**Comment by crisatmongo** [comment]
> Just wondering: should the base branch for this PR be `branding-master`?

When you say 'branding-master', Is that the alias for 'v0.13.25-branding.3', and if so, since that's been released, do I now update the existing branch to 'v0.13.26-branding' or create a whole new branch rebased off the latest release (which was not branding release)?

**Comment by schmalliso** [comment]
@crisatmongo I'll get a new branding-master set up this morning for you to repoint the PR at 😁.

**Comment by schmalliso** [comment]
> - I wasn't able to find a quiz example. Could you share what that looks like with the new palette?

@allisonmui9 As far as I know, there are no quizzes in use in the docs -- the feature hasn't had any uptake from the content team thus far.

**Comment by schmalliso** [comment]
> okay! gotcha. Should we prepare for a future where a writer uses the widget and rebrand it? Is there a way to do that? Or would you prefer to leave it as is until someone uses it?

We have a separate ticket for the quiz widget ([DOP-2588](https://jira.mongodb.org/browse/DOP-2588)) so we can wrangle it then, I think, if that works for you?

**Comment by allisonmui9** [comment]
> > okay! gotcha. Should we prepare for a future where a writer uses the widget and rebrand it? Is there a way to do that? Or would you prefer to leave it as is until someone uses it?
> 
> We have a separate ticket for the quiz widget ([DOP-2588](https://jira.mongodb.org/browse/DOP-2588)) so we can wrangle it then, I think, if that works for you?

works for me! thanks

**Comment by crisatmongo** [comment]
> Server
> 
> * It's looking like the top margin before the 'What is MongoDB' header has become quite squished. Does that have something to do with this change or something else?

It appears that change occurs when switching from version 6.0 to 6.1. Since the squishing is already occurring in production, I don't believe it is related but can investigate in a separate ticket if you'd like to revert it.

> Guides
> 
> * Yes, I agree with Allison on the colors of the chapter tags.
> * Let's change the colors to: background green light 3 and text MDB black.
> * The same applies to this screenshot! Let's change the chapter tag color to background green light 3 and text MDB black. Let's change the check, line, and lightning bolt to green dark 1.
> 
> Screen Shot 2022-09-20 at 10 59 58 AM
> 

Here is the staging link for the requested changes: https://docs-mongodbcom-integration.corp.mongodb.com/master/guides/cris.newsome/DOP-2575/

The background was already the new green light 3, but I changed the text to MDB black.
image

The font of the chapter list numbers is still green dark 3, as it is in Figma, but let me know if you'd prefer those to match.

The guides list progress bar has been updated so that the completed checkmarks, line, and lightning bolt are all now green dark 1.
image

**Pull request merged**
