### PR TITLE
DOP-4698: Hide IA header on Search

### PR DESCRIPTION
**Pull request by mmeigs**
### Stories/Links:

DOP-4598

### Current Behavior:

https://www.mongodb.com/docs/search/

### Staging Links:

https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/no-ia-header/landing/matt.meigs/DOP-4698-hide-ia-header/search/index.html

### Notes:

Consolidates the two pages that need to hide the Docs Home. Includes Search page now.

### README updates

- - [ ] This PR introduces changes that should be reflected in the README, and I have made those updates.
- - [x] This PR does not introduce changes that should be reflected in the README

### CODE REVIEW

**Review by seungpark — COMMENTED** [review]
minor nitpick, there seems to be a minor padding with the SideNavGroup first div here for `side-nav-group-header`:

image


Can we perhaps remove this with a className={cx(css``)} passed to IA component (and passed down to SideNavItem?)

Also, getting this minor warning when running this locally:
```
head-export-handler-for-browser.js:72 Warning: Failed prop type: Invalid prop `header` of type `boolean` supplied to `IA`, expected a single ReactElement.
```

**Review by anabellabuckvar — APPROVED** [review]
LGTM! Thanks for doing this

**Comment by mmeigs** [comment]
> minor nitpick, there seems to be a minor padding with the SideNavGroup first div here for `side-nav-group-header`:
> 
> image
> 
> Can we perhaps remove this with a className={cx(css``)} passed to IA component (and passed down to SideNavItem?)
> 
> Also, getting this minor warning when running this locally:
> 
> ```
> head-export-handler-for-browser.js:72 Warning: Failed prop type: Invalid prop `header` of type `boolean` supplied to `IA`, expected a single ReactElement.
> ```

I've fixed the padding!! And I don't see the warning on my machine. Everything works well, and full builds do not show it.

**Comment by seungpark** [comment]
> > minor nitpick, there seems to be a minor padding with the SideNavGroup first div here for `side-nav-group-header`:
> > image
> > Can we perhaps remove this with a className={cx(css``)} passed to IA component (and passed down to SideNavItem?)
> > Also, getting this minor warning when running this locally:
> > ```
> > head-export-handler-for-browser.js:72 Warning: Failed prop type: Invalid prop `header` of type `boolean` supplied to `IA`, expected a single ReactElement.
> > ```
> 
> I've fixed the padding!! And I don't see the warning on my machine. Everything works well, and full builds do not show it.

LGTM. i think that warning is unrelated to this PR, forgot to update comment!

**Review by seungpark — APPROVED** [review]

**Pull request merged**
