### PR TITLE
DOP-4632: Make feedback widget submitted links use LG Typography

### PR DESCRIPTION
**Pull request by i80and**
### Stories/Links:

DOP-4632

This page isn't reflected in Figma, so I ran this change by Amelia Short!

### Staging Screenshot:

image
image

### README updates

- - [ ] This PR introduces changes that should be reflected in the README, and I have made those updates.
- - [x] This PR does not introduce changes that should be reflected in the README

### CODE REVIEW

**Review by mmeigs — COMMENTED** [review]
I think the SupportCase anchor tag needs to change to a Link as well to ingest DarkMode. (first screenshot below)

We should probably ask Amelia and other design folks about the icon for the screenshot, it seems a lil rough in dark mode. (second screenshot below)
Screenshot 2024-06-17 at 4 13 38 PM
Screenshot 2024-06-17 at 4 13 48 PM

**Comment by i80and** [comment]
Hm, indeed, the icon IS a little funky winkerbean. Removing a `<rect>` element maxes it match the Figma design, but I'll check in first. Good catch!

**Comment by i80and** [comment]
image
image

**Review by mmeigs — APPROVED** [review]
Looks wonderful!

**Review by seungpark — APPROVED** [review]

**Pull request merged**
