### PR TITLE
DOP-1691: Update On This Page box

### PR DESCRIPTION
**Pull request by rayangler**
[[JIRA Ticket](https://jira.mongodb.org/browse/DOP-1691)]
[[Realm Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/raymundrodriguez/DOP-1691/)]
[[Long box example](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/raymundrodriguez/DOP-1691/admin/api/v3)]
[[Atlas Staging](https://docs-mongodbcom-staging.corp.mongodb.com/snooty-setup/cloud-docs/raymundrodriguez/DOP-1691/tutorial/connect-to-your-cluster)]

Things to keep in mind:
- This implementation does NOT utilize the `contents` directive that writers use on pages. Some pages that did not originally use `.. contents::` now do, by default. It might be worth considering utilizing post-processing on the parser to let the writer control when to have the component on the page.
- Pages that used to have more than one `contents` directive now only show 1.
- Default max depth of contents is now 2 to avoid having too many items listed in the contents box.
- The `On This Page` box now only says `On This Page`.

EDIT: Pages no longer show `On This Page` by default. Before looking for heading nodes, we now check to make sure a contents directive exists.

EDIT 2: Added Atlas staging link and updated Realm's.

### CODE REVIEW

**Review by sophstad — COMMENTED** [review]
> This implementation does NOT utilize the contents directive that writers use on pages.

Interesting, I'm not sure if this was an intended effect of this ticket. Would it be possible to only show the sidebar on pages that include a `contents` directive?

**Comment by eshwer** [comment]
Question: Do we know how this On this page box with behave if there is a language switcher present as well? cc. @sophstad

**Comment by eshwer** [comment]
Visuals: LGTM
Re: _"Pages no longer show On This Page by default. Before looking for heading nodes, we now check to make sure a contents directive exists.:"_ 
Does this match the mindset of the writers (e.g. they would add when they want it) or in the past did it show on default no matter what?

**Comment by rayangler** [comment]
@eshwer 

> Does this match the mindset of the writers (e.g. they would add when they want it) or in the past did it show on default no matter what?

Yes! In the past, writers would have to use the `.. contents::` directive to show the old `On This Page` box. Not every page uses it nor shows it so not showing it by default is probably the way to go.

> Do we know how this On this page box with behave if there is a language switcher present as well?

Just included a link to an [example page](https://docs-mongodbcom-staging.corp.mongodb.com/snooty-setup/cloud-docs/raymundrodriguez/DOP-1691/tutorial/connect-to-your-cluster) with a language switcher present.

**Review by eshwer — APPROVED** [review]
Ah ok looks great, thanks!

**Comment by eshwer** [comment]
Wait ah undo approval -- it is weird that "Select Your Language" and "On this Page" font looks different. Could we pick one and use the same. cc @allisonmui9 waiting allisons feedback about which one to go with

**Pull request closed without merging**
