### PR TITLE
DOP-2578: update LG card to v6

### PR DESCRIPTION
**Pull request by seungpark**
### Stories/Links:

[DOP-2578](https://jira.mongodb.org/browse/DOP-2578)
[LG CARD](https://www.mongodb.design/component/card/example/)

### Current Behavior:
[docs landing](https://www.mongodb.com/docs/)
[docs landing/develop applications](https://www.mongodb.com/docs/develop-applications/)
[atlas docs](https://www.mongodb.com/docs/atlas/)
[server manual docs](https://www.mongodb.com/docs/manual/)
[realm docs](https://www.mongodb.com/docs/realm/)

### Staging Links:

[docs landing](https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/seung.park/DOP-2578/
)
[docs landing/develop applications](https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/seung.park/DOP-2578/develop-applications/)
[atlas docs](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/seung.park/DOP-2578/
)
[server manual docs](https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/seung.park/DOP-2578/
)
[realm docs](https://docs-mongodbcom-integration.corp.mongodb.com/master/realm/seung.park/DOP-2578/)

### Notes:

- fairly simple change. no breaking changes from card changes, package update may suffice

### CODE REVIEW

**Review by allisonmui9 — DISMISSED** [review]
Could you add a staging link for the navigation landing pages? 
https://www.mongodb.com/docs/develop-applications/

**Comment by seungpark** [comment]
> Could you add a staging link for the navigation landing pages? https://www.mongodb.com/docs/develop-applications/

https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/seung.park/DOP-2578/develop-applications/
here you go! :) adding to PR description

**Comment by allisonmui9** [comment]
Looks good - small comments: 
- On hover, the shadow creates a faint box. Is that from us or from LG? Attached a photo.
- In the navigation landing page - the type auto-updated to Euclid and then decreased font size. Was that an effect of this update or something else? 
- Question for @casthewiz / @schmalliso, if there's content updates that need to happen as a result of the component updates, how should I go about that? For example, b/c the card has SUCH rounded corners now, some of the content is spilling over.
Screen Shot 2022-07-26 at 4 51 23 PM

**Comment by seungpark** [comment]
> Looks good - small comments:
> 
> * On hover, the shadow creates a faint box. Is that from us or from LG? Attached a photo.
> * In the navigation landing page - the type auto-updated to Euclid and then decreased font size. Was that an effect of this update or something else?
> * Question for @casthewiz / @schmalliso, if there's content updates that need to happen as a result of the component updates, how should I go about that? For example, b/c the card has SUCH rounded corners now, some of the content is spilling over.
> 
> Screen Shot 2022-07-26 at 4 51 23 PM

seems like the box shadow is intended by [LG component](https://www.mongodb.design/component/card/example/), it shows the box shadow on hover when the card is a link, which corresponds to the samples above

as per 2) which is the navigation landing page? 😬 [do you mean this one?](https://docs-mongodbcom-integration.corp.mongodb.com/master/landing/seung.park/DOP-2578/) not seeing the euclid here

**Comment by seungpark** [comment]
discussed offline with @schmalliso. the typography changes coming in with this LG update is desired. typography as a whole will be handled in DOP-2583.

**Review by gjchong25 — APPROVED** [review]
LGTM pending Allison's approval! Looks fine across different screen sizes. 

I will say- the box shadow that exists on prod seems less pronounced than the ones we're seeing for the newer, more rounded Cards. Not sure if that's an issue though ..

**Comment by rayangler** [comment]
The cards in the staging links look good to me, but I did notice that the differences in styles were causing a flash between styles for cards on the Guides site ([staging link](https://docs-mongodbcom-integration.corp.mongodb.com/master/guides/raymundrodriguez/DOP-2578/index.html)). I don't recall the context behind overwriting the border radiuses ourselves, but we could potentially remove them for the [Chapter cards](https://github.com/mongodb/snooty/blob/77cbaea06b5c23a5d29eea4b9451bdcfff24923f/src/components/Chapters/Chapter.js#L17) and the [Learning Card](https://github.com/mongodb/snooty/blob/77cbaea06b5c23a5d29eea4b9451bdcfff24923f/src/components/Chapters/RightColumn.js#L21). (cc. @allisonmui9 - I want to make sure that this sounds right given your designs for the Guides landing page)

**Comment by rayangler** [comment]
Also wanted to point out that the Feedback widget looks very roundish now in the staging links. Not sure if it's due to the card upgrade?
Screen Shot 2022-07-28 at 3 16 37 PM

**Comment by seungpark** [comment]
@rayangler thanks i overlooked all the child Card's that inherit from Leafy Green cards. Looking into verifying FeedbackCard, RightColumn, and DriversIndexTiles, Operation, ... + more. will put staging links for these components

**Comment by rayangler** [comment]
> @rayangler thanks i overlooked all the child Card's that inherit from Leafy Green cards. Looking into verifying FeedbackCard, RightColumn, and DriversIndexTiles, Operation, ... + more. will put staging links for these components

Thanks, Seung! For what it's worth, `Operation` may be good to look at for completion, but might not be necessary. I'm not sure if that component is still actually actively used anywhere and we have yet to formally deprecate/remove it. Let me know if you need any help with staging anything

**Comment by seungpark** [comment]
@allisonmui9 adding a few more staging links to verify these changes with cards. found a few places this may be affected in docs UI:

[drivers on prod](https://www.mongodb.com/docs/drivers/) vs [drivers for staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/drivers/seung.park/DOP-2578/)

[tutorials on prod](https://www.mongodb.com/docs/guides/) vs [tutorials for staging](https://docs-mongodbcom-integration.corp.mongodb.com/master/guides/seung.park/DOP-2578/). these have a slight diff in the [chapter summary](https://www.mongodb.com/docs/guides/atlas/account/) as well

**Comment by seungpark** [comment]
> > @rayangler thanks i overlooked all the child Card's that inherit from Leafy Green cards. Looking into verifying FeedbackCard, RightColumn, and DriversIndexTiles, Operation, ... + more. will put staging links for these components
> 
> Thanks, Seung! For what it's worth, `Operation` may be good to look at for completion, but might not be necessary/critical. I'm not sure if that component is still actually actively used anywhere and we have yet to formally deprecate/remove it. Let me know if you need any help with staging anything

CMIIW but Operation component is not used by any doc repo. exhausted docs content repos for directive, openapi objects, so didn't include in staging. also did not find any Quiz components in use either. thanks for the tips, much appreciated!

**Comment by seungpark** [comment]
closed due to https://github.com/mongodb/snooty/pull/673

**Pull request closed without merging**
