### PR TITLE
DOP-2221 - Monospace styling on latest MacOS and Chrome

### PR DESCRIPTION
**Pull request by carooobregon**
### Stories/Links:

DOP-2221

### Staging Links:
[Docs Staging
](https://docs-mongodbcom-staging.corp.mongodb.com/master/docs/carolinao/DOP--2221/tutorial/getting-started/)
### Notes:
**Problem**.- Inline code was getting rendered by the browser's default settings rather than adhering to LeafyGreen standards since the `Literal` code component was wrapping its children in between code tags.
**Solution**.- Imported `InlineCode` from LeafyGreen to `Literal.js` to return an `InlineCode` component rather than code tag.
Also deleted` .code .tt ` styling in css since it was overriding the color that needs to be inherited from body ( 21313C )

### CODE REVIEW

**Review by allisonmui9 — APPROVED** [review]
LGTM!!

**Comment by rayangler** [comment]
@allisonmui9 What do you think about headings with `InlineCode` in them? The font sizes aren't consistent. Would it be better to make them the same size? ([Example](https://docs-mongodbcom-staging.corp.mongodb.com/master/docs/carolinao/DOP--2221/reference/read-concern-local/))

**Comment by carooobregon** [comment]
> @allisonmui9 What do you think about headings with `InlineCode` in them? The font sizes aren't consistent. Would it be better to make them the same size? ([Example](https://docs-mongodbcom-staging.corp.mongodb.com/master/docs/carolinao/DOP--2221/reference/read-concern-local/))

This is what it looks like with the font-size values respecting the inheritance [Docs Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/docs/carolinao/DOP--2221/)

**Comment by allisonmui9** [comment]
Omg. initial thought - looks kind of cray haha. Let me think about what to do & get back to you tomorrow!

**Comment by schmalliso** [comment]
Once we figure out with @allisonmui9 what to do with the (admittedly slightly odd-looking 😉 ) headings and are in theory ready for merge, can y'all message me to set up a review by a few docsteam members? This is a major aesthetic change and I want to ensure that we're not bamboozling any table formatting or whatever that we didn't anticipate.

**Comment by carooobregon** [comment]
Just for reference- this is how it looks like with 16px font size (LeafyGreen standards)

Screen Shot 2021-06-11 at 9 19 26

**Comment by carooobregon** [comment]
Re the feedback we got in the [ #ask-design-systems channel ](https://mongodb.slack.com/archives/CM90JQHEJ/p1623421598087500)

> I’d recommend going with the font size that matches the context where it’s used (aka use the header font size).
> That’s a great call-out, and something it’s worth us supporting more directly. I’ll make a ticket for this.
> https://jira.mongodb.org/browse/PD-1440

How should I proceed with this? Should I leave it as it is, use the ` font-size: unset;` CSS property in a class (the way I'm doing it in the staged env atm) or just wait until they fix the Leafy-Green `Literal` component?

**Comment by allisonmui9** [comment]
Let's go forward with what you have now - using the font size of the context / header. Thank you!

**Review by allisonmui9 — APPROVED** [review]

**Comment by schmalliso** [comment]
@jeff-allen-mongo When you're back in the office, can you have a look at Caro's staging branch and let us know if there's anything super weird here for the server docs? We're switching the inline code bits to leafygreen's inline code component, which is aesthetically different and thus I wanted to check before we mess up a bunch of tables :) Thanks!

**Review by rayangler — APPROVED** [review]

**Comment by jeff-allen-mongo** [comment]
Hi all, thanks for putting these changes together! I think overall this change is great, but I'm not sure about the monospace in headings and in the left-hand ToC.

- Example of a heading with monospace: [Aggregation Pipeline Optimization](https://docs-mongodbcom-staging.corp.mongodb.com/master/docs/carolinao/DOP--2221/core/aggregation-pipeline-optimization/#--project-or--unset-or--addfields-or--set-----match-sequence-optimization)

- Also, the way "mongosh" and "mongo" look in the left-hand nav look a bit... odd? I'm no designer, though. Screenshot: 
Screen Shot 2021-06-15 at 12 41 22 PM

I don't know if this is possible, but my preference would be to not have the little box around the monospaced text in headings or in the left-hand nav. Maybe @allisonmui9 has thoughts on this?

**Comment by carooobregon** [comment]
[NEW PR](https://github.com/mongodb/snooty/pull/434)

**Pull request closed without merging**
