### PR TITLE
Update leafygreen-ui/tabs to v8

### PR DESCRIPTION
**Pull request by seungpark**
### Stories/Links:

[DOP-2577](https://jira.mongodb.org/browse/DOP-2577)
[LG component](https://www.mongodb.design/component/tabs/example/)

### Current Behavior:

Atlas docs on Production: https://www.mongodb.com/docs/atlas/
Server manual docs on Prod: https://www.mongodb.com/docs/manual/
Realm docs on Prod: https://www.mongodb.com/docs/realm/sdk/node/install/

### Staging Links:

Atlas docs on Staging: https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/seung.park/DOP-2577/
Server manual docs Staging: https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/seung.park/DOP-2577/
Realm docs on Staging: https://docs-mongodbcom-integration.corp.mongodb.com/master/realm/seung.park/DOP-2577/sdk/node/install/

### Notes:
Updated the visual to be v8 but there are some functional changes in leafygreen-ui/tabs mainly `disabled, default, href, to` that should be to snooty-parser as well as snooty. @casthewiz is the best practice here to follow up with another story?
UPDATE: follow up issue created here https://jira.mongodb.org/plugins/servlet/samlsso?redirectTo=%2Fbrowse%2FDOP-3148

- there is a specificity for page.options.template === 'product-landing', realm docs are not one of them, and hence does not apply snooty scope's styling on top of LG tabs

### CODE REVIEW

**Review by gjchong25 — COMMENTED** [review]
It seems like the text on the tabs shown in [LG](https://www.mongodb.design/component/tabs/example/) should still be centered? Besides that, it looks fine to me. I would maybe create staging links for some other major docs properties as well just for good measure like Manual, Realm, and/or Landing to ensure that we're seeing the desired behavior.

**Comment by seungpark** [comment]
> It seems like the text on the tabs shown in [LG](https://www.mongodb.design/component/tabs/example/) should still be centered? Besides that, it looks fine to me.

I'm not sure if that is meant to be centered, since the LG component is missing the flex-grow property. @allisonmui9 can you verify 1) if these tab titles should be left / center aligned and 2) tabs' total width should take full width of tablist container

(screenshot shows LG tabs with flex property applied:)
image

**Comment by allisonmui9** [comment]
- It should be center aligned. I'm not sure why it's missing on mongodb.design. 
- Re: take full width of tablist container: @rayangler or @gjchong25 would know better here and know the details. I would say to mirror just whatever is on production. 
- Additionally, we should use the 16px variant for the tab component. It's for better readability.

**Comment by seungpark** [comment]
@gjchong25 i updated the centering and also updated the overflow (since font weight has been updated)

updating PR with staging links for Manual, Realm, and Landing

**Comment by seungpark** [comment]
@gjchong25 updated with server manual docs and realm docs. skipped the landing docs because they were no tabs found in the pages.

with that said, @casthewiz is there a reason that snooty only targets `page.options.template === 'product-landing'` pages? (see staging link for realm for non product landing version of tabs, it is using pure LG tabs) if not, will remove this specificity

**Review by gjchong25 — COMMENTED** [review]
Generally LGTM pending Cassidy's response about the product landing question - it seems from looking at Realm docs on production that the new Tab styling should be applied here as well.

**Comment by casthewiz** [comment]
@gjchong25 and @seungpark [These](https://docs.google.com/document/d/13nl7VosWePqKCSU3liQ0uZnMvmM1KWMcn4aYaHnSYfM/edit#) [links](https://wiki.corp.mongodb.com/pages/viewpage.action?pageId=124684540) have more detail, but that boolean effectively exists to apply styling specific to landing page templates. I wouldn't remove it, and I wouldn't modify outside of specifically fixing an observed visual regression or odd behavior.

**Comment by seungpark** [comment]
thanks @casthewiz . seems like the tabs component update should be a documentation wide change after discussion with @allisonmui9. updated the PR and updating the staging link (for realm example)

**Pull request merged**
