### PR TITLE
DOP-2881: Rebrand and upgrade OpenAPI Redoc component

### PR DESCRIPTION
**Pull request by rayangler**
### Stories/Links:

DOP-2881

### Current Behavior:

[Cloud Admin API](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/)
[Atlas App Services Admin API](https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/)

### Staging Links:

[Cloud Admin API](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/raymundrodriguez/DOP-2881/reference/api-resources-spec/index.html)
[Atlas App Services Admin API](https://docs-mongodbcom-integration.corp.mongodb.com/master/atlas-app-services/raymundrodriguez/DOP-2881/admin/api/v3/index.html)

### Notes:
* Moved Redoc's `theme` object and most custom CSS to a separate file for organizational purposes.
* Took this as an opportunity to upgrade the frontend's version of `redoc`. This will allow the frontend to continue building OpenAPI content pages on the client side that will be consistent with the forked instance of Redoc we will be using in the future. Version-specific custom css selectors were modified accordingly.
* Certain components could not be/are difficult to change given the Redoc component's customization options ~~(such as headings)~~. Feel free to leave a comment or reach out if a certain component can also be changed.
* Also removed a console log statement leftover in a test. If we should keep it, feel free to let me know.

### CODE REVIEW

**Review by mmeigs — APPROVED** [review]
The new theme looks beautiful, and from what I can tell, the code looks good to me! But I would maybe wait for someone else's approval who has more knowledge on this than I? Up to you!

**Review by seungpark — APPROVED** [review]
this looks great! much more legible and the inverse of color in code blocks looks soft

as for this comment

> Certain components could not be/are difficult to change given the Redoc component's customization options (such as headings). Feel free to leave a comment or reach out if a certain component can also be changed.

can headings also be targeted by their redoc specific classnames? not familiar with this but seeing this consistent classname for page headers `sc-fubCfw` as noted in the stylesheet line 109

**Comment by rayangler** [comment]
> can headings also be targeted by their redoc specific classnames? not familiar with this but seeing this consistent classname for page headers sc-fubCfw as noted in the stylesheet line 109

`sc-fubCfw` is shared with other headings, but this did help me realize that the title heading has a generated classname that can be used to help differentiate. Updating staging links right now and will push up changes when finished!

**Review by allisonmui9 — CHANGES_REQUESTED** [review]
Just some small nits! Could you check if you can update the following? 
https://docs.google.com/document/d/1S9UCSvWw_NMPkDH43ENniYOwF2n29jWbWeZKfaogL74/edit?usp=sharing

Thank you! Let me know if you have any questions!

**Comment by rayangler** [comment]
@allisonmui9 Just updated staging links with the feedback! Let me know if I'm missing something or if there's anything else you notice

**Pull request merged**
