### PR TITLE
DOP-5181: Upgrade Chatbot to 0.10.2

### PR DESCRIPTION
**Pull request by mmeigs**
### Stories/Links:

DOP-5181

### Current Behavior:

[Landing](https://mongodb.com/docs/)

### Staging Links:

[Landing](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/collapse-expanded/landing/matt.meigs/DOP-5181-chatbot/index.html)

### Notes:

Updated Chatbot. Need to be on VPN to test on staging.

### README updates

- - [ ] This PR introduces changes that should be reflected in the README, and I have made those updates.
- - [x] This PR does not introduce changes that should be reflected in the README

### CODE REVIEW

**Review by rayangler — COMMENTED** [review]
~~I think this pretty much lgtm in terms of functionality, but I did notice that the like/dislike icons seem off center. Do we know if this is an issue with the latest version, or is this only happening on the docs site for some reason (this doesn't currently happen on prod)?~~

Screen Shot 2024-12-04 at 1 53 36 PM

EDIT: Ignore this. GH had some weird issue.

**Review by rayangler — COMMENTED** [review]
I think this pretty much lgtm in terms of functionality, but I did notice that the like/dislike icons seem off center. Do we know if this is an issue with the latest version, or is this only happening on the docs site for some reason (this doesn't currently happen on prod)?

Screen Shot 2024-12-04 at 1 53 36 PM

**Comment by mmeigs** [comment]
> I think this pretty much lgtm in terms of functionality, but I did notice that the like/dislike icons seem off center. Do we know if this is an issue with the latest version, or is this only happening on the docs site for some reason (this doesn't currently happen on prod)?
> 
> Screen Shot 2024-12-04 at 1 53 36 PM

Oh boy, it's us. I wonder what in the world this was for...
https://github.com/mongodb/snooty/blob/77c54afd797b1162171e6b530b442bf7a2a9d802/src/styles/mongodb-docs.css#L388

**Comment by mmeigs** [comment]
New staging link with style change:

https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/matt-example-sdk/java/matt.meigs/DOP-5181-chatbot/index.html

**Pull request merged**
