### PR TITLE
DOP-1778 - Update Body Content Color

### PR DESCRIPTION
**Pull request by carooobregon**
### Stories/Links:

DOP-1778 - Update Body Content Color

### Staging Links:

[Docs Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/docs/carolinao/DOP-1778/)
### Notes:

- Made modifications to css stored in mongodb-docs.css to apply font color changes

### CODE REVIEW

**Review by rayangler — APPROVED** [review]
LGTM! Tagging @allisonmui9 for a design perspective

**Comment by allisonmui9** [comment]
mostly looks good to me! 
A few comments: 
- I think the headings are using an outdated color. #313030
- Sorry I misspoke in the ticket. Can we use leafy green base black: #061621 for all body copy instead? 

Otherwise looks good!!

**Comment by rayangler** [comment]
Should we be using #61621? LeafyGreen [Typography](https://www.mongodb.design/component/typography/example/) shows body as #21313C. Just wanted to double-check for my understanding! @allisonmui9

**Comment by allisonmui9** [comment]
ooh darn! you're right :') keep at 21313c then! Can we update the headers?

**Comment by carooobregon** [comment]
@allisonmui9 Yeah for sure! To #21313C, correct? 



21313C
--

**Comment by allisonmui9** [comment]
yes!

**Comment by carooobregon** [comment]
Heading colors changed ! 
[Updated Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/docs/carolinao/DOP-1778/)

**Review by allisonmui9 — APPROVED** [review]
looks great!! LGTM! Thanks for doing this :)

**Review by rayangler — APPROVED** [review]
LGTM!

**Pull request merged**
