### PR TITLE
DOP-5029: CTAs should initialize in dark mode preference

### PR DESCRIPTION
**Pull request by mayaraman19**
### Stories/Links:

DOP-5029

Updates `Banner.js` and `CTABanner.js`.

### Current Behavior:

[CTA Banner](https://www.mongodb.com/docs/manual/reference/operator/)
[App Services Deprecation](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/atlas/app-services/deprecation/#std-label-app-services-deprecation)

### Staging Links:

[CTA Banner](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4683/docs/maya/DOP-5029/reference/operator/index.html)
[Test Banner Page](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4973-example/cloud-docs/maya/DOP-5029/test-banner/index.html)
[App Services Deprecation](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/atlas-app-services/maya/DOP-5029/deprecation/index.html)

### README updates

- - [ ] This PR introduces changes that should be reflected in the README, and I have made those updates.
- - [x] This PR does not introduce changes that should be reflected in the README

### CODE REVIEW

**Review by mmeigs — COMMENTED** [review]
It really does look great. Okay, I know this is so annoying, but since we're doing this anyway - could you also do the :before: and the svg so that those colors don't flash in light mode too? 
And there's one odd thing happening... in the [first link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4683/docs/maya/DOP-5029/reference/operator/index.html), the "You are" initialize in dark blue... I'm somehow guessing it's because of the anchor tag, but I really am not sure!

**Comment by biancalaube** [comment]
Hey Maya, I noticed 3 small things  in the that maybe could be fixed but Im not sure if they are blockers or not 
1. [CTA Banner](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4683/docs/maya/DOP-5029/reference/operator/index.html) : I noticed that the text “You can” on refresh goes from dark blue to the respective color for dark/light mode. I noticed it also flashes the dark blue in light mode.
2. I noticed  for just regular banners ( [Test Banner Page](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4973-example/cloud-docs/maya/DOP-5029/test-banner/index.html) ) that the left handside background color still flashes light mode before going to dark mode. 
3. On the [App Services Deprecation](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/atlas-app-services/maya/DOP-5029/deprecation/index.html) page the size of the font changes on reload. I don’t really know if that needs to be a fix in this ticket but just something I thought would be good to point out.

**Comment by mayaraman19** [comment]
@biancalaube the behavior seems to happen in preprd as well, so I'm going to file a ticket for this!

**Comment by biancalaube** [comment]
Thanks for doing that Maya, LGTM! :)

**Review by biancalaube — APPROVED** [review]

**Review by mmeigs — APPROVED** [review]
Oh so beautiful

**Pull request merged**
