### PR TITLE
DOP-4634: update Figure and corresponding components

### PR DESCRIPTION
**Pull request by seungpark**
### Stories/Links:

DOP-4634

### Current Behavior:

[current figure in cloud docs](https://www.mongodb.com/docs/atlas/atlas-ui/collections/#view-collections)
[staged changes with flag turned off](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/no-dark-mode/cloud-docs/seung.park/DOP-4634/atlas-ui/collections/index.html#view-collections)

### Staging Links:

[staged cloud docs with figure example](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/DOP-4634/atlas-ui/collections/index.html#view-collections)

### Notes:
- Figure and corresponding parts should be acceptable in dark mode (caption, full screen modal)

### README updates

- - [ ] This PR introduces changes that should be reflected in the README, and I have made those updates.
- - [X] This PR does not introduce changes that should be reflected in the README

### CODE REVIEW

**Review by mmeigs — COMMENTED** [review]
In the staged site, the Figure doesn't seem to have the "click to enlarge" caption or the capability to expand with a lightbox. Is that expected?

**Comment by seungpark** [comment]
> In the staged site, the Figure doesn't seem to have the "click to enlarge" caption or the capability to expand with a lightbox. Is that expected?

ah must have been an old stage. re-staged with current commits !

**Comment by seungpark** [comment]
> > > > In the staged site, the Figure doesn't seem to have the "click to enlarge" caption or the capability to expand with a lightbox. Is that expected?
> > > 
> > > 
> > > ah must have been an old stage. re-staged with current commits !
> > 
> > 
> > Now it doesn't have dark mode :) I'll dev locally and look at it!
> 
> 🤦 i had the flag off locally for testing no regression. restaging!

done!

**Review by mmeigs — APPROVED** [review]
LGTM!

**Pull request merged**
