### PR TITLE
DOP-4567: remove fixed height for image in lightbox

### PR DESCRIPTION
**Pull request by seungpark**
### Stories/Links:

DOP-4567

### Current Behavior:

[original slack message of k8s docs shows figure with distorted image 1](https://preview-mongodbjuliamongo.gatsbyjs.io/docs-k8s-operator/om-ha/tutorial/om-diagram-multi-cluster/)

[example 2 from k8s docs](https://preview-mongodbjuliamongo.gatsbyjs.io/docs-k8s-operator/om-ha/tutorial/om-nw-lb-mesh-multi-cluster/#diagram-example-1--external-load-balancer)

[atlas example of lighthouse figure](https://www.mongodb.com/docs/atlas/atlas-search/create-index/)

### Staging Links:

[k8s docs example 1 with staged changes](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/om-ha/docs-k8s-operator/seung.park/DOP-4567/tutorial/om-diagram-multi-cluster/index.html)

[staged example 2 from k8s docs](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/om-ha/docs-k8s-operator/seung.park/DOP-4567/tutorial/om-nw-lb-mesh-multi-cluster/index.html)

[atlas example updated](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/seung.park/DOP-4567/atlas-search/create-index/index.html)

### README updates

- - [ ] This PR introduces changes that should be reflected in the README, and I have made those updates.
- - [X] This PR does not introduce changes that should be reflected in the README

### CODE REVIEW

**Review by mmeigs — COMMENTED** [review]
This looks so much better! 

Two things: 
- Can we change the `navbarHeight` theme constant to `95px` rather than `88px` while we're here? I think the recent upgrade must have made it taller.
- I almost want to ask design (or just do it ourselves) if we can make the padding less? Some of these diagrams would benefit from getting more space? But idk, that's so non-blocking.

**Comment by seungpark** [comment]
> This looks so much better!
> 
> Two things:
> 
> * Can we change the `navbarHeight` theme constant to `95px` rather than `88px` while we're here? I think the recent upgrade must have made it taller.
> * I almost want to ask design (or just do it ourselves) if we can make the padding less? Some of these diagrams would benefit from getting more space? But idk, that's so non-blocking.

good catch! updated the navbarHeight and updated the staging links. as for the padding - i mentioned [a comment ](https://jira.mongodb.org/browse/DOP-4567?focusedCommentId=6289076&focusedId=6289076&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-6289076) but do not want this to be a blocker to get this pushed through the door!

**Comment by mmeigs** [comment]
> > This looks so much better!
> > Two things:
> > 
> > * Can we change the `navbarHeight` theme constant to `95px` rather than `88px` while we're here? I think the recent upgrade must have made it taller.
> > * I almost want to ask design (or just do it ourselves) if we can make the padding less? Some of these diagrams would benefit from getting more space? But idk, that's so non-blocking.
> 
> good catch! updated the navbarHeight and updated the staging links. as for the padding - i mentioned [a comment ](https://jira.mongodb.org/browse/DOP-4567?focusedCommentId=6289076&focusedId=6289076&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-6289076) but do not want this to be a blocker to get this pushed through the door!
> 
> Update: Approved by Liz!

Great! And the staging site looks great! But... I don't think you pushed up the changes you made

**Comment by seungpark** [comment]
> > > This looks so much better!
> > > Two things:
> > > 
> > > * Can we change the `navbarHeight` theme constant to `95px` rather than `88px` while we're here? I think the recent upgrade must have made it taller.
> > > * I almost want to ask design (or just do it ourselves) if we can make the padding less? Some of these diagrams would benefit from getting more space? But idk, that's so non-blocking.
> > 
> > 
> > good catch! updated the navbarHeight and updated the staging links. as for the padding - i mentioned [a comment ](https://jira.mongodb.org/browse/DOP-4567?focusedCommentId=6289076&focusedId=6289076&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-6289076) but do not want this to be a blocker to get this pushed through the door!
> > Update: Approved by Liz!
> 
> Great! And the staging site looks great! But... I don't think you pushed up the changes you made

pushed! thanks for the nudge <3

**Review by mmeigs — APPROVED** [review]

**Pull request merged**
