### PR TITLE
DOP-4548: Fix CTA banner icon placement

### PR DESCRIPTION
**Pull request by mmeigs**
### Stories/Links:

DOP-4548

### Current Behavior:

[Prod](https://www.mongodb.com/docs/manual/aggregation/)

### Staging Links:

[Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/matt.meigs/DOP-4548-cta-banner/aggregation/index.html)

### Notes:

This makes the icon fit nicely no matter how many lines of text are in the banner.

### README updates

- - [ ] This PR introduces changes that should be reflected in the README, and I have made those updates.
- - [x] This PR does not introduce changes that should be reflected in the README

### CODE REVIEW

**Review by mayaraman19 — COMMENTED** [review]
one small nit: when i first click on the staging link, the icon is initially offset then moves into place. I'm wondering if this might have to do with the `position: absolute` styling on the LG icon?

**Comment by mmeigs** [comment]
> Staging

Very nice catch, @mayaraman19 !! Thanks

**Review by mayaraman19 — COMMENTED** [review]
one more nit, sorry 😭 when I resize the browser to be small so the banner lines wrap, the circle around the icon gets a bit squished. 

image

**Comment by mayaraman19** [comment]
ok sorry one I SWEAR FINAL TINY nit: can the `margin-left` be changed to `15px` instead of `10px`? I find at `10px` the margin between the icon and text is sliiiiiightly smaller than it is in prod/uneven with the margin on the left side of the icon. TYSM 😭😭😭😭😭

**Review by mayaraman19 — APPROVED** [review]
LGTM!! thank u <3

**Pull request merged**
